Document: libpredict2
Title: Debian libpredict2 Manual
Author: <insert document author here>
Abstract: This manual describes what libpredict2 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/libpredict2/libpredict2.sgml.gz

Format: postscript
Files: /usr/share/doc/libpredict2/libpredict2.ps.gz

Format: text
Files: /usr/share/doc/libpredict2/libpredict2.text.gz

Format: HTML
Index: /usr/share/doc/libpredict2/html/index.html
Files: /usr/share/doc/libpredict2/html/*.html
