SOURCES = main.c
SOURCES += ../../src/orbit.c
SOURCES += ../../src/sdp4.c
SOURCES += ../../src/sgp4.c
SOURCES += ../../src/unsorted.c
SOURCES += ../../src/vec3.c

INCLUDES += -I ../../src

all:
	gcc $(SOURCES) $(INCLUDES) -Wall -lm -o basic
